### ISSUE TITLE
Auto-score & Auto-pickup in teleoperated period using odometry

### ISSUE THREAD

**Issue by ehamwey** [WHS-FRC-3467/Skip-5.13#43]
Navigating to scoring and pickup positions in teleop can be aided by automation & odometry. This would encompass several smaller tasks that would need to work in tandem, therefore I'm labeling this an epic: 

For North Shore event, so we can collect data:
- [ ] https://github.com/WHS-FRC-3467/Skip-5.13/issues/36 Limelight 3D AprilTag data fed into SwerveDrivePoseEstimator Kalman filter to correct odometry drift using `addVisionMeasurement()` 
- [ ] #44 Logging to track & debug odometry over time ([AdvantageKit](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/INSTALLATION.md)) 

For the Greater Boston event, so we can actually run auto-score: 
- [ ] Software (a webserver?) to select exact scoring positions on the grid intuitively, such as 6328's node selector [Robot parser](https://github.com/Mechanical-Advantage/RobotCode2023/blob/main/src/main/java/org/littletonrobotics/frc2023/subsystems/objectivetracker/ObjectiveTracker.java) | [webserver](https://github.com/Mechanical-Advantage/RobotCode2023/tree/main/src/main/deploy/nodeselector) | [post explaining how it works](https://www.chiefdelphi.com/t/frc-6328-mechanical-advantage-2023-build-thread/420691/74?u=emileh)
- [ ] On-the-fly path generation to go to grid scoring positions or substation from anywhere on the field while avoiding opponent's zones using [PathPlanner OTF path generation](https://github.com/mjansen4857/pathplanner/wiki/PathPlannerLib:-Java-Usage#on-the-fly-generation)
